import { pool, query } from '../../config/dbconfig';

const dbGetSession = async (id) => {
  const { rows } = await query('SELECT * FROM session WHERE user_id=$1', [id]);
  return rows[0];
};

const dbPostSession = async ({
  id,
  user_id,
  is_paid,
  object,
  after_expiration,
  allow_promotion_codes,
  amount_subtotal,
  amount_total,
  automatic_tax_enabled,
  automatic_tax_status,
  billing_address_collection,
  cancel_url,
  client_reference_id,
  consent,
  consent_collection,
  created,
  currency,
  custom_text_shipping_address,
  custom_text_submit,
  customer,
  customer_creation,
  customer_details_address,
  customer_details_email,
  customer_details_name,
  customer_details_phone,
  customer_details_tax_exempt,
  customer_details_tax_ids,
  customer_email,
  expires_at,
  invoice,
  invoice_creation,
  livemode,
  locale,
  metadata,
  mode,
  payment_intent,
  payment_link,
  payment_method_collection,
  payment_method_options,
  payment_method_types,
  payment_status,
  phone_number_collection,
  phone_number_collection_enabled,
  recovered_from,
  setup_intent,
  shipping_address_collection,
  shipping_cost,
  shipping_details,
  shipping_options,
  status,
  submit_type,
  subscription,
  success_url,
  total_details,
  url,
}) => {
  const { rows } = await query(
    // eslint-disable-next-line max-len
    'INSERT INTO session(id,userid,is_paid,object,after_expiration,allow_promotion_codes,amount_subtotal,amount_total,automatic_tax_enabled,automatic_tax_status,billing_address_collection,cancel_url,client_reference_id,consent,consent_collection,created,currency,custom_text_shipping_address,custom_text_submit,customer,customer_creation,customer_details_address,customer_details_email,customer_details_name,customer_details_phone,customer_details_tax_exempt,customer_details_tax_ids,customer_email,expires_at,invoice,invoice_creation,livemode,locale,metadata,mode,payment_intent,payment_link,payment_method_collection,payment_method_options,payment_method_types,payment_status,phone_number_collection,phone_number_collection_enabled,recovered_from,setup_intent,shipping_address_collection,shipping_cost,shipping_details,shipping_options,status,submit_type,subscription,success_url,total_details,url ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51,$52,$53,$54,$55) returning *',
    [
      id,
      user_id,
      is_paid,
      object,
      after_expiration,
      allow_promotion_codes,
      amount_subtotal,
      amount_total,
      automatic_tax_enabled,
      automatic_tax_status,
      billing_address_collection,
      cancel_url,
      client_reference_id,
      consent,
      consent_collection,
      created,
      currency,
      custom_text_shipping_address,
      custom_text_submit,
      customer,
      customer_creation,
      customer_details_address,
      customer_details_email,
      customer_details_name,
      customer_details_phone,
      customer_details_tax_exempt,
      customer_details_tax_ids,
      customer_email,
      expires_at,
      invoice,
      invoice_creation,
      livemode,
      locale,
      metadata,
      mode,
      payment_intent,
      payment_link,
      payment_method_collection,
      payment_method_options,
      payment_method_types,
      payment_status,
      phone_number_collection,
      phone_number_collection_enabled,
      recovered_from,
      setup_intent,
      shipping_address_collection,
      shipping_cost,
      shipping_details,
      shipping_options,
      status,
      submit_type,
      subscription,
      success_url,
      total_details,
      url,
    ],
  );
  return rows[0];
};

export { dbGetSession, dbPostSession };
