GET http://localhost:3000/realestate/checkout-session/s_test_a18pXfNA81IYvZvSMzDkeWX1VTRm1SZ6UCjEg0GOPkW37GzwvKXjTgzWmm
################################
POST http://localhost:3000/realestate/create-checkout-session
################################
GET http://localhost:3000/user/stripe/session/cs_test_a1de0c3Ggcn8SUky19RwrPsuUNbxd7xVvarC4bYQ7pSA3rZWPsJQP59TAF
################################
GET http://localhost:3000/user/stripe/user/8153a1fc-e958-4658-9451-e55df5a4db45
################################
GET http://localhost:3000/user
################################
PATCH http://localhost:3000/user/stripe/c80ac11c-780b-4627-9cb4-06166039b188
Content-Type: application/json

{
    "session_id":"cs_test_a1TfAt7CigWorQ4TDemz0ZkN79x2cCSqpdDQWh5Z9JDSbERBK1yIcjnXRe"
}